# fly.toml app configuration file generated for os-mqtt-gateway on 2026-01-02T13:49:43-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'os-mqtt-gateway'
primary_region = 'dfw'

[build]
  dockerfile = './Dockerfile'

[[vm]]
  memory = '1gb'
  cpus = 1
  memory_mb = 1024

[[mounts]]
  source = "mosquitto_data"
  destination = "/mosquitto/data"

[[services]]
  internal_port = 1883
  protocol = "tcp"

[[services.ports]]
  port = "10000"
